/* PROPRIETARY — Copyright (c) 2026. All rights reserved. */
import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
import{demoEvents,demoSanctions,INVESTIGATION_DISCLAIMER}from"@insurance/engine-core";import{rdsScenarios}from"@insurance/insurance-lenses";
import{accumulations,createSyntheticPortfolio,exposureWeightedAlerts,generateDailyBrief,money,requirePro,screenOwnershipChain,stressScenario,type Entitlement}from"@insurance/overlay-pro";

function App(){const[entitlement,setEntitlement]=useState<Entitlement>({userId:"anonymous",tier:"anonymous",source:"none"});const[client,setClient]=useState("all");const book=useMemo(()=>createSyntheticPortfolio(),[]);const scoped=useMemo(()=>client==="all"?book:{sites:book.sites.filter(x=>x.clientId===client),entities:book.entities.filter(x=>x.clientId===client),vessels:book.vessels.filter(x=>x.clientId===client),supplyChains:book.supplyChains.filter(x=>x.clientId===client)},[book,client]);
  if(entitlement.tier!=="pro")return <main className="login"><div className="login-card"><div className="mark">S+</div><span>PORTFOLIO OVERLAY · PROPRIETARY</span><h1>Turn global signals into<br/>your book’s priorities.</h1><p>The shared open engine, weighted by your declared exposure. Pro content is unavailable until the server-side entitlement check succeeds.</p><div className="credentials"><b>Seeded demo</b><code>pro@example.test</code><code>demo-pro</code></div><button onClick={()=>setEntitlement({userId:"demo-pro",tier:"pro",source:"demo",expiresAt:"2099-01-01T00:00:00Z"})}>Sign in to synthetic pro book</button><small>Stripe test adapter is fail-closed until TODO(me) keys are configured.</small></div></main>;
  try{requirePro(entitlement)}catch{return null}const alerts=exposureWeightedAlerts(demoEvents,scoped);const accumulation=accumulations(scoped);const sanctioned=book.entities.find(e=>e.name.includes("Northstar"))!;const ownership=screenOwnershipChain({...book.entities[0],ultimateParentId:sanctioned.id,ownershipPercent:60},book.entities,demoSanctions);const scenario=stressScenario(scoped,rdsScenarios[0].footprint.value,rdsScenarios[0].severity.value);
  return <main><header><div className="logo">S+</div><div><b>SIGNALWATCH PRO</b><small>PORTFOLIO SITUATION ROOM</small></div><nav><a className="active">Overview</a><a>Alerts</a><a>Accumulation</a><a>Screening</a><a>Scenarios</a><a>Imports</a></nav><select value={client}onChange={e=>setClient(e.target.value)}><option value="all">All clients</option><option value="client-a">Client A branded view</option><option value="client-b">Client B branded view</option><option value="client-c">Client C branded view</option></select><button onClick={()=>setEntitlement({userId:"anonymous",tier:"anonymous",source:"none"})}>Sign out</button></header>
    <section className="top"><div><span>GOOD MORNING · 21 SEP 2026</span><h1>What changed in your book</h1><p>{generateDailyBrief(alerts,scoped)}</p></div><div className="book"><b>SYNTHETIC BOOK</b><div>{scoped.sites.length}<small>sites</small></div><div>{scoped.entities.length}<small>entities</small></div><div>{scoped.vessels.length}<small>vessels</small></div><div>{scoped.supplyChains.length}<small>supply chains</small></div><i>Source: Synthetic portfolio generator v1 · 06:00 UTC</i></div></section>
    <section className="metrics"><div><span>DECLARED SITE EXPOSURE</span><b>{money(scoped.sites.reduce((s,x)=>s+x.sumInsured,0))}</b><small>Synthetic portfolio generator v1 · 06:00 UTC</small></div><div><span>EXPOSURE IN ACTIVE FOOTPRINTS</span><b className="amber">{money(alerts.reduce((s,x)=>s+x.exposureAtRisk,0))}</b><small>NOAA fixture + portfolio overlay · 06:00 UTC</small></div><div><span>OPEN BOOK ALERTS</span><b>{alerts.length}</b><small>Exposure-weighted method · 06:00 UTC</small></div><div><span>SCREENING FLAGS</span><b className="red">1</b><small>OFAC SLS synthetic fixture · 06:00 UTC</small></div></section>
    <div className="grid"><section className="panel alerts"><div className="head"><div><span>RANKED BY SEVERITY × EXPOSURE</span><h2>Portfolio alerts</h2></div><em>{alerts.length} exposure-bearing</em></div>{alerts.map(a=><article key={a.id}><div className="rank">01</div><div><b>{a.eventTitle}</b><small>{a.touchedSiteIds.length} sites inside 650 km proximity footprint</small><i>NOAA IBTrACS fixture + Synthetic portfolio generator · 06:00 UTC</i></div><div><strong>{money(a.exposureAtRisk)}</strong><span>exposure at risk</span><small>{Math.round(a.severity*100)} × declared exposure</small></div></article>)}{!alerts.length&&<p>No alert: no exposure intersects an active event.</p>}<footer>{INVESTIGATION_DISCLAIMER}</footer></section>
      <section className="panel"><div className="head"><div><span>BOOK-WIDE CONCENTRATION</span><h2>Top accumulations</h2></div></div><h4>BY GEOGRAPHY</h4>{accumulation.byCountry.slice(0,5).map(([k,v],i)=><div className="bar"key={k}><label>{k}<b>{money(v)}</b></label><span><i style={{width:`${100-i*13}%`}}/></span></div>)}<h4>BY PERIL</h4>{accumulation.byPeril.slice(0,4).map(([k,v],i)=><div className="bar"key={k}><label>{k}<b>{money(v)}</b></label><span><i style={{width:`${95-i*16}%`}}/></span></div>)}<small className="src">Synthetic portfolio generator v1 · 06:00 UTC</small></section>
      <section className="panel"><div className="head"><div><span>OWNERSHIP-CHAIN SCREENING</span><h2>Human review required</h2></div><em className="danger">{ownership.status}</em></div><div className="screening"><b>{ownership.chain[0].entity.name}</b><span>↳ 60% owned by {sanctioned.name}</span><strong>Majority-owner match propagated</strong><small>OFAC SDN synthetic fixture · CYBER2 synthetic demo · 06:00 UTC</small></div><footer>{INVESTIGATION_DISCLAIMER}</footer></section>
      <section className="panel"><div className="head"><div><span>RDS STRESS TEST</span><h2>{rdsScenarios[0].name.value}</h2></div></div><div className="stress"><b>{money(scenario.exposureAtRisk)}</b><span>declared exposure in synthetic footprint</span><strong>{scenario.touchedSites.length} sites touched</strong></div><button>Open site-level results</button><small className="src">Insurance Lenses v1 method + Synthetic portfolio · 06:00 UTC</small><footer>{INVESTIGATION_DISCLAIMER}</footer></section>
    </div></main>}
createRoot(document.getElementById("root")!).render(<App/>);
